name: PUSH
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install hexo
        run: |
          npm install -g hexo-cli

      - name: Build project
        run: |
          hexo clean
          hexo g -d
