name: PUSH
on:
  push:
    branches:
      - master
env:
  NGINX_PATH: /var/www/blog/imrcrab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install hexo
        run: |
          npm install -g hexo-cli
          npm install -g gulp

      - name: Build project
        run: |
          hexo clean
          hexo g
          gulp
          hexo d
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BLOG_HOST }}
          username: ${{ secrets.BLOG_USERNAME }}
          port: ${{ secrets.BLOG_PORT }}
          key: ${{ secrets.BLOG_KEY }}
          source: "./public/*"
          target: "/var/"
      - name: mv ./public to outside
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.BLOG_HOST }}
          username: ${{ secrets.BLOG_USERNAME }}
          port: ${{ secrets.BLOG_PORT }}
          key: ${{ secrets.BLOG_KEY }}
          script: |
            rm -rf ${{ env.NGINX_PATH }}/*
            mkdir -p ${{ env.NGINX_PATH }}
            cp -R /var/public/* ${{ env.NGINX_PATH }}/
            rm -rf /var/public
      # - name: Upload File To COS
      #   run: |
      #     cd ./public
      #     chmod +x ../cos5upload
      #     ../cos5upload  --Path ./ --SecretID ${{ secrets.COS_TENCENT_ID }} --SecretKey ${{ secrets.COS_TENCENT_KEY }} --Region ${{ secrets.REGION }} --BucketName ${{ secrets.BUCKETNAME }} --ExcludeFilePaths css/:js/:lib/:live2dw/:images/
