name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      id: change_file
      with:
        token: ${{ secrets.TOKEN }}
    - name: Printing
      run: |
        echo "All:"
        echo '${{ steps.change_file.outputs.all }}'
        echo "Added:"
        echo "${{ steps.change_file.outputs.added }}"
        echo "Removed:"
        echo "${{ steps.change_file.outputs.removed }}"
        echo "Renamed:"
        echo "${{ steps.change_file.outputs.renamed }}"
        echo "Modified:"
        echo "${{ steps.change_file.outputs.modified }}"
        echo "Added+Modified:"
        echo "${{ steps.change_file.outputs.added_modified }}"
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "source"
        target: ${{ secrets.TARGET }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          ${{ secrets.EXEC_BASH_PUSH }}
          ${{ COMMENT_JS }}