name: PUSH
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install hexo
        run: |
          npm install -g hexo-cli
          npm install -g gulp

      - name: Build project
        run: |
          hexo clean
          hexo g
          gulp
          hexo d
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f /archives && 
                upload -r ./public/archives / &&
                delete -r -f /categories && 
                upload -r ./public/categories / && 
                delete -r -f /page && 
                upload -r ./public/page / &&
                delete -r -f /tags && 
                upload -r ./public/tags / &&
                delete -f index.html && 
                upload -r ./public/index.html / &&
                delete -f search.xml && 
                upload -r ./public/search.xml / &&
                delete -f baidusitemap.xml && 
                upload -r ./public/baidusitemap.xml / &&
                delete -f sitemap.xml && 
                upload -r ./public/sitemap.xml / &&
          secret_id: ${{ secrets.COS_TENCENT_ID }}
          secret_key: ${{ secrets.COS_TENCENT_KEY }}
          bucket: ${{ secrets.COS_TENCENT_NAME }}
          region:  ${{ secrets.COS_TENCENT_REGION }}
